name: Generate capabilities and config schema

on:
  push:
    branches:
      - main

jobs:
  generate_outputs:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELENG_GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Build
        run: go build -o connector ./cmd/baton-databricks

      - name: Run and save config output
        run: ./connector config > config_schema.json

      - name: Run and save capabilities output
        env:
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
          BATON_ACCOUNT_ID: ${{ secrets.BATON_ACCOUNT_ID }}
          BATON_WORKSPACES: ${{ secrets.BATON_WORKSPACES }}
          BATON_WORKSPACE_TOKENS: ${{ secrets.BATON_WORKSPACE_TOKENS }}
        run: ./connector capabilities > baton_capabilities.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Updating baton config schema and capabilities."
          add: |
            config_schema.json
            baton_capabilities.json